add test for invalid_tag
pulibrary/marc_cleanup pull request #110
Opened 2024-02-14 20:18 UTC by pmgreen

2024-02-14 20:38 UTC, Beck-Davis commented on spec/record_level/validate_marc_spec.rb
>      it 'finds the invalid tag' do
Not sure what this block is doing. The code only checks for non-numerical characters in the field tag. This block isn't really necessary.

2024-02-14 21:30 UTC, Beck-Davis requested changes
Separate methods should have separate test blocks under the `RSpec.describe`. We should avoid nesting tests in unrelated methods (they don't call on each other).

2024-02-14 21:36 UTC, pmgreen commented
Ok, I wasn't sure whether validate_marc was the method in record_level.rb or whether it was the logical structure for tests.

2024-02-14 21:39 UTC, Beck-Davis commented
I double checked, it looks like we've been creating separate files for each method to be tested, even if the method is smaller, unless they are directly related or one calls the other. So for this one, it can have its own file.

2024-02-14 22:25 UTC, pmgreen commented
The `invalid_tag?` method is currently only checking for non-numeric characters within a tag (not length, etc.). Maybe rename it to `non_numeric_tag?`.

2024-02-15 14:23 UTC, Beck-Davis approved these changes
looks good

2024-02-15 14:24 UTC, merged

2024-02-15 14:25 UTC, Beck-Davis commented
> The `invalid_tag?` method is currently only checking for non-numeric characters within a tag (not length, etc.). Maybe rename it to `non_numeric_tag?`.

True. We can make a ticket for it.