test demonstrating that after leaderfix is executed on fixture record position 8 has become a space character
pulibrary/marc_cleanup pull request #49
Opened 2023-10-31 15:30 UTC by Twade968

Acceptance criteria:

- [x] Modify marc_with_invalid_leader.xml fixture object to have an invalid value in position 8 of the leader
- [x] Write a test demonstrating that after leaderfix is executed on this fixture record, position 8 has become a space character

2023-10-31 15:39 UTC, mzelesky requested changes

2023-10-31 15:39 UTC, mzelesky commented on spec/fixtures/malformed_leaders/marc_with_valid_leader_2.xml
The fixture for the record with the valid leader has been removed. The original file needs to be retained, otherwise the valid leader test will fail.

2023-11-02 12:55 UTC, Twade968 commented on spec/fixtures/malformed_leaders/marc_with_valid_leader_2.xml
marc_with_valid_leader.xml is still present, and all test are passing. Not sure where this file came from but it does not look like we need it.

2023-11-02 13:21 UTC, mzelesky approved these changes
This looks good.

2023-11-02 13:21 UTC, merged