new fixture for issue 63
pulibrary/marc_cleanup pull request #65
Opened 2023-11-09 21:06 UTC by Beck-Davis

Co-authored by Peter Green <pmgreen@users.noreply.github.com>

2023-11-09 21:22 UTC, mzelesky commented
I would like to have the test included in this pull request along with the fixture. So you can make additional commits within the same branch to write the test to accompany the fixture.

2023-11-09 21:27 UTC, mzelesky commented on spec/fixtures/fixed_fields/marc_with_bad_008.xml
> +        <controlfield tag="008">230519s1996    njua       k  000 0 eng d</controlfield>
I would like to have the 008 have a value that can be fixed. In the `fix_comp_008` method, that means that it has to be one of the following positions of the field:

audience (position 22 of `u` or `v` becomes `j`)
government publication indicator (position 28 of 'n' becomes 'o')

2023-11-14 15:57 UTC, Beck-Davis commented
The Fixture is updated and test created

2023-11-20 19:43 UTC, mzelesky requested changes
Minor changes needed, but the test is successful!

2023-11-20 19:43 UTC, mzelesky commented on spec/fixed_fields/comp_format_bad_008_spec.rb
> +RSpec.describe 'test  008 ' do
In the `describe` string, the name of the method you're testing should be there in general. In this case, we are testing the `bad_008?` method.

2023-11-20 19:43 UTC, mzelesky commented on spec/fixed_fields/comp_format_bad_008_spec.rb
> +    it 'knows that a record with bad 008 is invalid' do
This should specify that it's finding a bad computer 008.

2023-11-27 13:59 UTC, mzelesky approved these changes
Looks great!

2023-11-27 14:01 UTC, merged