Methods and test for 020 and ISBN clean up.
pulibrary/marc_cleanup pull request #83
Opened 2023-12-13 20:59 UTC by Beck-Davis

Methods to normalize ISBNs in field 020$a, move invalid ISBNs to 020$z, and move qualifying information from 020$a to 020$q.

Uses the following methods by Mark Zelesky <mzelesky@users.noreply.github.com>
`isbn10_to_13`
`checkdigit_10`
`checkdigit_13`
`isbn13_normalize`
`isbn_normalize`

2023-12-14 16:28 UTC, Beck-Davis commented
Closes #80

2023-12-14 18:55 UTC, mzelesky requested changes
2 more tests needed:
1. A valid ISBN-13 value.
2. An ISBN between 7 and 8 digits long that does not start with 978.

In addition, add a layer to the describe statements so all the move_invalid_isbn tests are nested.
Make sure the ISBN prefix constant is frozen (`.freeze`)

2023-12-14 18:55 UTC, mzelesky commented on lib/marc_cleanup/variable_fields.rb
> +  stem + checkdigit
According to coveralls, line 67 is not currently tested. That means the tests aren't reaching this line in the code. I'll leave a summary of the cases that need to be tested in a summary comment for the review.

2023-12-14 18:55 UTC, mzelesky commented on lib/marc_cleanup/variable_fields.rb
> +    raw_isbn = raw_isbn.ljust(9, '0')
This line of code is also not tested.

2023-12-15 15:53 UTC, Beck-Davis commented
Changes addressed. Ready for review.

2023-12-15 15:59 UTC, merged